CREATE TABLE ADMS_CODED_TRANSLATION_ENTRIES (
  record_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  translation_name   VARCHAR2(200 CHAR) NOT NULL,
  entry_key          NUMBER(10),
  entry_key_text     VARCHAR2(200 CHAR) NOT NULL,
  short_name         VARCHAR2(400 CHAR),
  text_value         VARCHAR2(4000 CHAR),
  text1_value        VARCHAR2(4000 CHAR),
  image_name         VARCHAR2(400 CHAR),
  default_image_name VARCHAR2(400 CHAR),
  read_only_flag     NUMBER(1) DEFAULT 0 NOT NULL,
  source_system      VARCHAR2(100 CHAR) DEFAULT 'github' NOT NULL,
  source_commit      VARCHAR2(64 CHAR),
  sync_run_id        VARCHAR2(36 CHAR) NOT NULL,
  added_on           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ADMS_CODED_TRANSLATION_ENTRIES PRIMARY KEY (record_id)
);

CREATE INDEX IDX_ADMS_CODED_TRANSLATION_LOOKUP
  ON ADMS_CODED_TRANSLATION_ENTRIES (translation_name, entry_key_text, added_on);

CREATE INDEX IDX_ADMS_CODED_TRANSLATION_RUN
  ON ADMS_CODED_TRANSLATION_ENTRIES (sync_run_id);
